// Idea bank: future videos, ready to be made as soon as a track arrives.
// Each idea chains 2–3 stories from topics.js. Drop a track into music/inbox/ and
// `npm run daily` gives it to the next idea that has no track yet (in this order).
// Add new ideas at the end; ids must be unique and are also the track's file name.

export const IDEAS = [
  { id: 'black-hole-birth', title: 'How a Black Hole Is Born', subtitle: 'the death of a giant star', topics: ['massive-star-death', 'inside-black-hole'] },
  { id: 'day-the-sun-dies', title: 'The Day the Sun Dies', subtitle: 'and what comes after', topics: ['sun-life-cycle', 'end-of-universe'] },
  { id: 'first-light-to-gold', title: 'From First Light to Gold', subtitle: 'the first stars forged everything', topics: ['first-stars', 'origin-of-gold'] },
  { id: 'our-cosmic-address', title: 'Our Cosmic Address', subtitle: 'where the Milky Way came from, and where it goes', topics: ['galaxy-formation', 'milky-way-andromeda'] },
  { id: 'a-planet-is-born', title: 'A Planet Is Born', subtitle: 'from dust to a living world', topics: ['solar-system', 'habitable-earth'] },
  { id: 'neutron-stars-and-gold', title: 'Neutron Stars and Gold', subtitle: 'the most violent forge in space', topics: ['neutron-star', 'origin-of-gold'] },
  { id: 'stardust-to-earth', title: 'Stardust to Earth', subtitle: 'we are made of dead stars', topics: ['origin-of-gold', 'habitable-earth'] },
  { id: 'giants-and-dwarfs', title: 'Giants and Dwarfs', subtitle: 'the biggest and the longest-living stars', topics: ['massive-star-death', 'red-dwarfs'] },
  { id: 'big-bang-to-black-holes', title: 'From the Big Bang to Black Holes', subtitle: 'how the darkest objects took over', topics: ['galaxy-formation', 'inside-black-hole'] },
  { id: 'jupiter-and-the-sun', title: 'Jupiter and the Sun', subtitle: 'the king and the star', topics: ['sun-life-cycle', 'jupiter-giant'] },
  { id: 'earth-and-moon', title: 'The Earth and the Moon', subtitle: 'born from a collision', topics: ['moon-formation', 'habitable-earth'] },
  { id: 'the-last-galaxies', title: 'The Last Galaxies', subtitle: 'how galaxies will end', topics: ['milky-way-andromeda', 'end-of-universe'] },
  { id: 'cosmic-collisions', title: 'Cosmic Collisions', subtitle: 'when worlds and galaxies crash', topics: ['moon-formation', 'milky-way-andromeda'] },
  { id: 'the-first-black-holes', title: 'The First Black Holes', subtitle: 'monsters of the young universe', topics: ['first-stars', 'inside-black-hole'] },
  { id: 'birth-of-the-milky-way', title: 'Birth of the Milky Way', subtitle: 'how our galaxy filled with stars', topics: ['galaxy-formation', 'star-birth'] },
  { id: 'the-sun-and-its-planets', title: 'The Sun and Its Planets', subtitle: 'one star, eight worlds', topics: ['sun-life-cycle', 'solar-system'] },
  { id: 'habitable-worlds', title: 'Habitable Worlds', subtitle: 'where else could life exist?', topics: ['habitable-earth', 'red-dwarfs'] },
  { id: 'gas-giants', title: 'Gas Giants', subtitle: 'the kings of the outer solar system', topics: ['jupiter-giant', 'solar-system'] },
  { id: 'galaxies-through-time', title: '13 Billion Years of Galaxies', subtitle: 'from the first light to Andromeda', topics: ['first-stars', 'milky-way-andromeda'] },
  { id: 'beginning-and-end', title: 'The Beginning and the End', subtitle: 'the first stars and the last', topics: ['first-stars', 'end-of-universe'] },
  { id: 'when-stars-die', title: 'When Stars Die', subtitle: 'white dwarfs and supernovae', topics: ['sun-life-cycle', 'massive-star-death'] },
  { id: 'timeline-of-the-universe', title: 'The Timeline of the Universe', subtitle: 'from the Big Bang to the end', topics: ['galaxy-formation', 'solar-system', 'end-of-universe'] },
  { id: 'life-and-death-of-stars', title: 'Life and Death of Stars', subtitle: 'every stage, one journey', topics: ['star-birth', 'sun-life-cycle', 'massive-star-death'] },
  { id: 'most-extreme-objects', title: 'The Most Extreme Objects in Space', subtitle: 'neutron stars, black holes, kilonovae', topics: ['neutron-star', 'inside-black-hole', 'origin-of-gold'] },
  { id: 'planets-from-dust', title: 'Planets From Dust', subtitle: 'how the solar system was built', topics: ['solar-system', 'jupiter-giant', 'moon-formation'] },
  { id: 'cosmic-origins', title: 'Cosmic Origins', subtitle: 'the first stars, galaxies and suns', topics: ['first-stars', 'galaxy-formation', 'star-birth'] },
  { id: 'where-we-come-from', title: 'Where We Come From', subtitle: 'from star forges to a living planet', topics: ['origin-of-gold', 'solar-system', 'habitable-earth'] },
  { id: 'the-dark-future', title: 'The Dark Future', subtitle: 'the Sun, the galaxy and the universe', topics: ['sun-life-cycle', 'milky-way-andromeda', 'end-of-universe'] },
  { id: 'inside-a-nebula', title: 'Inside a Nebula', subtitle: 'where every star begins', topics: ['star-birth', 'first-stars'] },
  { id: 'red-dwarf-worlds', title: 'Red Dwarf Worlds', subtitle: 'planets around the quiet stars', topics: ['red-dwarfs', 'jupiter-giant'] },
  { id: 'gravity-engines', title: 'The Gravity Engines', subtitle: 'giants that shape space', topics: ['jupiter-giant', 'inside-black-hole'] },
  { id: 'born-from-the-stars', title: 'Born From the Stars', subtitle: 'how a cloud became a home', topics: ['star-birth', 'habitable-earth'] },
  { id: 'sun-vs-red-dwarfs', title: 'Our Sun vs Red Dwarfs', subtitle: 'which stars live the longest', topics: ['sun-life-cycle', 'red-dwarfs'] },
  { id: 'supernova-to-planets', title: 'From Supernova to Planets', subtitle: 'death that builds new worlds', topics: ['massive-star-death', 'solar-system'] },
  { id: 'pulsar-beats', title: 'Pulsar Beats', subtitle: 'the lighthouses of the universe', topics: ['neutron-star', 'first-stars'] },
  { id: 'andromeda-is-coming', title: 'Andromeda Is Coming', subtitle: 'the collision that will reshape our sky', topics: ['milky-way-andromeda', 'red-dwarfs'] },
  { id: 'how-earth-was-made', title: 'How Earth Was Made', subtitle: 'disk, impact, oceans', topics: ['solar-system', 'moon-formation', 'habitable-earth'] },
  { id: 'the-cosmic-cycle', title: 'The Cosmic Cycle', subtitle: 'stars are born, die and are reborn', topics: ['star-birth', 'massive-star-death', 'origin-of-gold'] },
  { id: 'beyond-the-horizon', title: 'Beyond the Horizon', subtitle: 'black holes and the far future', topics: ['inside-black-hole', 'end-of-universe', 'first-stars'] },
  { id: 'the-violent-universe', title: 'The Violent Universe', subtitle: 'explosions, collisions, collapse', topics: ['massive-star-death', 'moon-formation', 'milky-way-andromeda'] },
];
