// Content catalog (English). A topic is an ordered list of beats; each beat is one
// 3D scene plus the narration that plays over it. Scene types live in renderer/scenes.js.
// Add a topic here and the factory turns it into a long video and a set of Shorts.

const NEBULA_PALETTES = [
  ['#ff4f8b', '#4f7dff', '#ffb04f'],
  ['#5ef2ff', '#8a5bff', '#ff6fd8'],
  ['#ff7a3c', '#ffd36b', '#b03cff'],
  ['#3cff9e', '#3c8bff', '#ff3c6e'],
];

export const TOPICS = [
  {
    id: 'star-birth',
    title: 'How Stars Are Born',
    subtitle: 'from a cold cloud to a sun',
    beats: [
      { type: 'nebula', label: 'Molecular Cloud', camera: { dist: [140, 95], height: [30, 18], orbit: 0.04 },
        text: 'Every star begins in darkness. Cold clouds of gas and dust, hundreds of light years across, drift slowly between the stars of the galaxy.' },
      { type: 'nebula', label: 'Gravitational Collapse', params: { collapse: 1 }, camera: { dist: [110, 60], height: [25, 10], orbit: 0.06 },
        text: 'All it takes is a push, a distant supernova or a collision between clouds, and gravity takes over. The cloud breaks into clumps, and each one starts to fall in on itself.' },
      { type: 'protostar', label: 'Protostar', camera: { dist: [90, 55], height: [35, 14], orbit: 0.08 },
        text: 'Gas spirals into a disk and falls toward the center. The core heats up to millions of degrees, while jets of matter trillions of kilometers long blast out from its poles.' },
      { type: 'star', label: 'Ignition', params: { color: '#ffd38a', radius: 3, growTo: 6, colorTo: '#ffe2a8' }, camera: { dist: [60, 42], height: [8, 4], orbit: 0.05 },
        text: 'When the core reaches ten million degrees, hydrogen begins fusing into helium. Nuclear fusion pushes back against gravity, and a star is born.' },
      { type: 'star', label: 'Main Sequence', params: { color: '#ffe2a8', radius: 6 }, camera: { dist: [42, 30], height: [6, 2], orbit: 0.06 },
        text: 'Now it will stay stable for billions of years. Our Sun is in this phase right now, and it is this phase that gives planets their light and warmth.' },
    ],
  },
  {
    id: 'solar-system',
    title: 'How the Solar System Formed',
    subtitle: '4.6 billion years ago',
    beats: [
      { type: 'nebula', label: 'Solar Nebula', params: { collapse: 0.6 }, camera: { dist: [140, 90], height: [40, 20], orbit: 0.04 },
        text: 'Four point six billion years ago, where the Solar System is now, there was only a cloud of gas, enriched with heavy elements from earlier generations of stars.' },
      { type: 'protostar', label: 'Protoplanetary Disk', camera: { dist: [100, 70], height: [45, 25], orbit: 0.06 },
        text: 'The cloud collapsed and began to spin. The young Sun ignited at its center, surrounded by a flat disk of dust, ice and gas.' },
      { type: 'planetformation', label: 'Birth of the Planets', params: { planets: 5 }, camera: { dist: [120, 80], height: [55, 30], orbit: 0.05 },
        text: 'Dust grains stuck together into pebbles, pebbles into boulders, boulders into planetary embryos. Close to the Sun only rocky worlds survived, while beyond the frost line the gas giants grew.' },
      { type: 'planet', label: 'Young Earth', params: { kind: 'rock', molten: 1, colorA: '#1d4f8a', colorB: '#3f7a3a' }, camera: { dist: [34, 24], height: [6, 3], orbit: 0.08 },
        text: 'The young Earth was an ocean of molten magma. Only after hundreds of millions of years did it cool, forming a crust, an atmosphere and the first oceans.' },
      { type: 'planet', label: 'Gas Giant', params: { kind: 'gas', ring: true, colorA: '#b88a5a', colorB: '#f0dcb4' }, camera: { dist: [48, 34], height: [10, 6], orbit: 0.06 },
        text: 'Out on the edges, giants like Jupiter and Saturn gathered vast envelopes of hydrogen and helium, and they still shield the inner planets from comets today.' },
    ],
  },
  {
    id: 'sun-life-cycle',
    title: 'The Complete Life Cycle of the Sun',
    subtitle: 'from birth to white dwarf',
    beats: [
      { type: 'protostar', label: 'Birth', camera: { dist: [90, 60], height: [35, 15], orbit: 0.07 },
        text: 'The Sun was born from a collapsing cloud of gas. For its first few million years it was a protostar, wrapped in a disk of matter.' },
      { type: 'star', label: 'Adulthood: 10 Billion Years', params: { color: '#ffe2a8', radius: 6 }, camera: { dist: [45, 32], height: [6, 2], orbit: 0.06 },
        text: 'Today the Sun is about four and a half billion years old, roughly halfway through its life. Every second it turns six hundred million tons of hydrogen into helium.' },
      { type: 'star', label: 'Red Giant', params: { color: '#ffd08a', radius: 5, growTo: 18, colorTo: '#ff5a2a' }, camera: { dist: [70, 120], height: [8, 14], orbit: 0.04 },
        text: 'In about five billion years the hydrogen in its core will run out. The Sun will swell into a red giant, swallow Mercury and Venus, and scorch the Earth into a barren desert.' },
      { type: 'planetarynebula', label: 'Planetary Nebula', camera: { dist: [110, 80], height: [20, 12], orbit: 0.05 },
        text: 'Its outer layers will slowly drift off into space, forming a glowing planetary nebula, one of the most beautiful structures in the universe.' },
      { type: 'star', label: 'White Dwarf', params: { color: '#dfe8ff', radius: 1.4, flares: false }, camera: { dist: [22, 12], height: [3, 1], orbit: 0.05 },
        text: 'At the center, a core the size of Earth will remain: a white dwarf. It will glow with leftover heat for trillions of years, slowly fading away.' },
    ],
  },
  {
    id: 'massive-star-death',
    title: 'How Massive Stars Die',
    subtitle: 'supernova, neutron star, black hole',
    beats: [
      { type: 'star', label: 'Blue Giant', params: { color: '#9cc0ff', radius: 8 }, camera: { dist: [60, 42], height: [8, 4], orbit: 0.06 },
        text: 'Stars ten times more massive than the Sun live fast and bright. They burn through their fuel in just a few million years.' },
      { type: 'star', label: 'Red Supergiant', params: { color: '#ffb070', radius: 8, growTo: 22, colorTo: '#ff3a1a' }, camera: { dist: [80, 140], height: [10, 16], orbit: 0.04 },
        text: 'Near the end, such a star swells into a red supergiant. Layer by layer, its core forges heavier and heavier elements, all the way up to iron.' },
      { type: 'supernova', label: 'Supernova', camera: { dist: [60, 150], height: [10, 30], orbit: 0.05 },
        text: 'Iron yields no energy. In a fraction of a second the core collapses, and the star explodes as a supernova, outshining its entire galaxy for weeks.' },
      { type: 'blackhole', label: 'Black Hole', camera: { dist: [80, 50], height: [12, 6], orbit: 0.06 },
        text: 'If the leftover core is heavy enough, nothing can stop the collapse. A black hole is born, a place from which not even light can escape.' },
      { type: 'nebula', label: 'The Next Generation', params: { palette: NEBULA_PALETTES[2] }, camera: { dist: [140, 100], height: [25, 15], orbit: 0.04 },
        text: 'And the carbon, oxygen and iron thrown out by the blast become the raw material for new stars, new planets, and eventually, for us.' },
    ],
  },
  {
    id: 'galaxy-formation',
    title: 'How Galaxies Form',
    subtitle: 'from the Big Bang to the Milky Way',
    beats: [
      { type: 'bigbang', label: 'The Big Bang', camera: { dist: [60, 220], height: [10, 40], orbit: 0.05 },
        text: 'Thirteen point eight billion years ago, the entire universe was an unimaginably hot, dense point. Then it began to expand.' },
      { type: 'nebula', label: 'The First Clouds', params: { collapse: 0.8, palette: ['#6a8dff', '#9b6aff', '#c8d6ff'] }, camera: { dist: [150, 90], height: [30, 15], orbit: 0.04 },
        text: 'Tiny ripples in density grew. Dark matter pulled gas into enormous clouds, where the very first stars ignited.' },
      { type: 'galaxy', label: 'Protogalaxy', params: { form: 1, arms: 2 }, camera: { dist: [190, 150], height: [90, 60], orbit: 0.04 },
        text: 'Clouds merged, and their rotation slowly flattened the matter into a disk. Out of chaos, the first galaxies took shape.' },
      { type: 'galaxy', label: 'Spiral Arms', params: { arms: 4, twist: 3.6 }, camera: { dist: [170, 120], height: [110, 50], orbit: 0.05 },
        text: 'Spiral arms are density waves rolling through the disk. Gas gets squeezed inside them, and that is where most new stars are born.' },
      { type: 'blackhole', label: 'Heart of the Galaxy', params: { color: '#ffb36b' }, camera: { dist: [90, 55], height: [14, 6], orbit: 0.06 },
        text: 'And at the center of almost every large galaxy hides a supermassive black hole. The one in the Milky Way weighs as much as four million Suns.' },
    ],
  },
  {
    id: 'first-stars',
    title: 'The First Stars in the Universe',
    subtitle: 'giants made of pure hydrogen',
    beats: [
      { type: 'bigbang', label: 'Cosmic Dawn', camera: { dist: [60, 200], height: [10, 40], orbit: 0.05 },
        text: 'After the Big Bang, the universe cooled into a dark fog of hydrogen and helium. For a hundred million years, there was no light at all.' },
      { type: 'nebula', label: 'Dark Matter Halos', params: { collapse: 0.9, palette: ['#6a8dff', '#9b6aff', '#c8d6ff'] }, camera: { dist: [150, 80], height: [30, 12], orbit: 0.05 },
        text: 'Invisible clumps of dark matter pulled the gas together. With no heavy elements to cool it, the clouds had to grow enormous before they could collapse.' },
      { type: 'star', label: 'Population III Stars', params: { color: '#9cc0ff', radius: 5, growTo: 11, colorTo: '#bcd4ff' }, camera: { dist: [80, 55], height: [10, 4], orbit: 0.06 },
        text: 'The first stars were monsters, hundreds of times the mass of the Sun, blazing blue and burning out in just a few million years.' },
      { type: 'supernova', label: 'The First Explosions', camera: { dist: [60, 160], height: [10, 30], orbit: 0.05 },
        text: 'Their deaths were titanic explosions that seeded the universe with the first carbon, oxygen and iron.' },
      { type: 'galaxy', label: 'The First Galaxies', params: { form: 1, arms: 3 }, camera: { dist: [190, 140], height: [90, 55], orbit: 0.04 },
        text: 'From those ashes, smaller and longer-lived stars formed, gathering into the first galaxies. Every star we see today descends from them.' },
    ],
  },
  {
    id: 'inside-black-hole',
    title: 'What Happens Inside a Black Hole',
    subtitle: 'beyond the event horizon',
    beats: [
      { type: 'supernova', label: 'Collapse', params: { remnant: 'blackhole' }, camera: { dist: [60, 140], height: [10, 25], orbit: 0.05 },
        text: 'When a giant star dies, its core can collapse so completely that gravity wins over every other force in nature.' },
      { type: 'blackhole', label: 'The Accretion Disk', camera: { dist: [110, 70], height: [18, 8], orbit: 0.06 },
        text: 'Gas falling toward a black hole is heated to millions of degrees, forming a blazing accretion disk that can outshine whole galaxies.' },
      { type: 'blackhole', label: 'The Event Horizon', params: { color: '#ffb36b' }, camera: { dist: [60, 30], height: [6, 2], orbit: 0.08 },
        text: 'The event horizon is the point of no return. Cross it, and every possible path leads only inward. Not even light can climb back out.' },
      { type: 'blackhole', label: 'Spaghettification', params: { color: '#ff6a3c' }, camera: { dist: [40, 18], height: [3, 1], orbit: 0.1 },
        text: 'Near a small black hole, the pull on your feet would be far stronger than on your head. You would be stretched thin, like spaghetti.' },
      { type: 'bigbang', label: 'The Singularity', camera: { dist: [200, 40], height: [30, 5], orbit: 0.05 },
        text: 'At the center, our equations break down. Is it a point of infinite density, or a door to physics we do not yet understand? No one knows.' },
    ],
  },
  {
    id: 'neutron-star',
    title: 'What Is a Neutron Star',
    subtitle: 'a city-sized atomic nucleus',
    beats: [
      { type: 'star', label: 'A Doomed Giant', params: { color: '#ffb070', radius: 8, growTo: 20, colorTo: '#ff3a1a' }, camera: { dist: [80, 130], height: [10, 16], orbit: 0.04 },
        text: 'A neutron star begins as a giant star, eight to twenty times the mass of the Sun, nearing the end of its life.' },
      { type: 'supernova', label: 'Core Collapse', camera: { dist: [60, 150], height: [10, 30], orbit: 0.05 },
        text: 'Its iron core collapses in less than a second. Electrons are crushed into protons, turning the core into a ball of neutrons.' },
      { type: 'star', label: 'Twenty Kilometers Wide', params: { color: '#bcd4ff', radius: 1.6, flares: false }, camera: { dist: [24, 12], height: [3, 1], orbit: 0.3 },
        text: 'What remains is just twenty kilometers wide, yet heavier than the Sun. A teaspoon of it would weigh a billion tons.' },
      { type: 'protostar', label: 'Pulsar', params: { color: '#a8c8ff' }, camera: { dist: [70, 45], height: [30, 12], orbit: 0.12 },
        text: 'Many neutron stars spin hundreds of times per second, sweeping beams of radiation across space like a cosmic lighthouse. We call them pulsars.' },
      { type: 'nebula', label: 'Supernova Remnant', params: { palette: ['#46e0c8', '#6a8dff', '#ff5a7a'] }, camera: { dist: [140, 100], height: [25, 15], orbit: 0.04 },
        text: 'Around them, the glowing debris of the explosion keeps expanding for thousands of years, like the famous Crab Nebula.' },
    ],
  },
  {
    id: 'origin-of-gold',
    title: 'Where Gold Comes From',
    subtitle: 'forged in colliding neutron stars',
    beats: [
      { type: 'star', label: 'Iron Is the Limit', params: { color: '#ffe2a8', radius: 6 }, camera: { dist: [45, 32], height: [6, 2], orbit: 0.06 },
        text: 'Ordinary stars can forge elements only up to iron. Gold, platinum and uranium need something far more violent.' },
      { type: 'blackhole', label: 'A Deadly Dance', params: { color: '#a8c8ff' }, camera: { dist: [100, 60], height: [20, 8], orbit: 0.12 },
        text: 'Two neutron stars orbit each other, spiraling closer for millions of years as they radiate away energy in gravitational waves.' },
      { type: 'supernova', label: 'Kilonova', camera: { dist: [60, 160], height: [10, 30], orbit: 0.05 },
        text: 'When they finally collide, they release a kilonova. In seconds, a flood of neutrons builds heavy elements, including several Earth masses of gold.' },
      { type: 'nebula', label: 'Scattered Treasure', params: { palette: ['#ffd36b', '#ff7a3c', '#ffe9b0'] }, camera: { dist: [140, 100], height: [25, 15], orbit: 0.04 },
        text: 'The gold spreads through the galaxy, mixing into the clouds that will form new stars and planets.' },
      { type: 'planet', label: 'Gold on Earth', params: { kind: 'rock', colorA: '#1d4f8a', colorB: '#3f7a3a' }, camera: { dist: [34, 24], height: [6, 3], orbit: 0.08 },
        text: 'So every gold ring on Earth is older than the Solar System, the debris of a cosmic collision billions of years ago.' },
    ],
  },
  {
    id: 'moon-formation',
    title: 'How the Moon Formed',
    subtitle: 'the giant impact',
    beats: [
      { type: 'planetformation', label: 'A Crowded System', params: { planets: 6 }, camera: { dist: [120, 80], height: [55, 30], orbit: 0.05 },
        text: 'Four and a half billion years ago, the young Solar System was crowded with growing planets on crossing orbits.' },
      { type: 'planet', label: 'Proto-Earth', params: { kind: 'rock', molten: 1, colorA: '#4a3a30', colorB: '#7a5a40' }, camera: { dist: [36, 26], height: [6, 3], orbit: 0.08 },
        text: 'The early Earth was still molten. And a Mars-sized world, called Theia, was heading straight toward it.' },
      { type: 'supernova', label: 'The Giant Impact', camera: { dist: [60, 130], height: [10, 25], orbit: 0.05 },
        text: 'The collision was so violent that it melted both worlds and blasted a huge cloud of vaporized rock into orbit.' },
      { type: 'planetformation', label: 'A Ring of Debris', params: { planets: 1 }, camera: { dist: [90, 60], height: [40, 20], orbit: 0.06 },
        text: 'That debris formed a ring around Earth. Within maybe just a few years, it clumped together into a new body.' },
      { type: 'planet', label: 'The Moon', params: { kind: 'rock', colorA: '#5a5a5a', colorB: '#b0b0b0' }, camera: { dist: [30, 20], height: [5, 2], orbit: 0.08 },
        text: 'The Moon was born. It still stabilizes our planet’s tilt and drives the tides, and it is slowly drifting away, a few centimeters every year.' },
    ],
  },
  {
    id: 'jupiter-giant',
    title: 'How Jupiter Became a Giant',
    subtitle: 'the king of the planets',
    beats: [
      { type: 'protostar', label: 'Beyond the Frost Line', camera: { dist: [110, 75], height: [45, 25], orbit: 0.06 },
        text: 'Far from the young Sun, beyond the frost line, water froze into ice, giving growing planets far more material to work with.' },
      { type: 'planetformation', label: 'A Rocky Core', params: { planets: 4 }, camera: { dist: [110, 75], height: [50, 28], orbit: 0.05 },
        text: 'Jupiter began as a core of rock and ice, about ten times the mass of Earth, in just a few million years.' },
      { type: 'planet', label: 'Runaway Growth', params: { kind: 'gas', colorA: '#b88a5a', colorB: '#f0dcb4' }, camera: { dist: [60, 38], height: [10, 5], orbit: 0.06 },
        text: 'Then its gravity began pulling in gas from the disk faster and faster. In a runaway process, it swallowed hundreds of Earth masses of hydrogen and helium.' },
      { type: 'planet', label: 'The Great Red Spot', params: { kind: 'gas', colorA: '#c26a3a', colorB: '#f4e2c4' }, camera: { dist: [30, 22], height: [4, 2], orbit: 0.08 },
        text: 'Today Jupiter is more than twice as massive as all other planets combined, wrapped in storms larger than Earth that have raged for centuries.' },
      { type: 'planetformation', label: 'Guardian of the System', params: { planets: 5 }, camera: { dist: [130, 90], height: [60, 35], orbit: 0.05 },
        text: 'Its gravity sculpted the asteroid belt and shaped the orbits of every planet, including our own.' },
    ],
  },
  {
    id: 'habitable-earth',
    title: 'How Earth Became Habitable',
    subtitle: 'from magma ocean to blue planet',
    beats: [
      { type: 'planet', label: 'Magma Ocean', params: { kind: 'rock', molten: 1, colorA: '#3a2a20', colorB: '#6a4a30' }, camera: { dist: [36, 26], height: [6, 3], orbit: 0.08 },
        text: 'Four and a half billion years ago, Earth was a ball of molten rock, battered by asteroids and wrapped in toxic gas.' },
      { type: 'planetformation', label: 'Water from Space', params: { planets: 4 }, camera: { dist: [120, 80], height: [55, 30], orbit: 0.05 },
        text: 'As the surface cooled, water arrived, released from the rocks themselves and delivered by icy asteroids from the outer system.' },
      { type: 'planet', label: 'The First Oceans', params: { kind: 'rock', colorA: '#123a6a', colorB: '#2a5a8a' }, camera: { dist: [34, 24], height: [6, 3], orbit: 0.08 },
        text: 'Rain fell for millions of years, filling the first oceans. Within them, simple chemistry slowly became life.' },
      { type: 'star', label: 'Powered by the Sun', params: { color: '#ffe2a8', radius: 6 }, camera: { dist: [45, 32], height: [6, 2], orbit: 0.06 },
        text: 'Tiny microbes learned to capture sunlight. Over two billion years, they filled the air with oxygen.' },
      { type: 'planet', label: 'The Blue Planet', params: { kind: 'rock', colorA: '#1d4f8a', colorB: '#3f7a3a' }, camera: { dist: [30, 20], height: [5, 2], orbit: 0.08 },
        text: 'A protective ozone layer formed, life crawled onto land, and a molten rock became the only world we know that is truly alive.' },
    ],
  },
  {
    id: 'red-dwarfs',
    title: 'Red Dwarfs: Stars That Live for Trillions of Years',
    subtitle: 'the quiet majority of the galaxy',
    beats: [
      { type: 'nebula', label: 'Small Beginnings', params: { collapse: 1, palette: ['#ff7a5a', '#ff4f8b', '#ffb04f'] }, camera: { dist: [110, 60], height: [25, 10], orbit: 0.06 },
        text: 'Not every cloud fragment grows into a Sun. Most end up much smaller, with less than half the Sun’s mass.' },
      { type: 'star', label: 'Red Dwarf', params: { color: '#ff6a3a', radius: 3 }, camera: { dist: [30, 20], height: [4, 2], orbit: 0.06 },
        text: 'These are red dwarfs, cool, dim stars. Three out of four stars in the Milky Way are red dwarfs, yet not one is visible to the naked eye.' },
      { type: 'star', label: 'Slow Burners', params: { color: '#ff5a2a', radius: 3, growTo: 3.4, colorTo: '#ff7a3a' }, camera: { dist: [25, 16], height: [3, 1], orbit: 0.08 },
        text: 'Their entire interior churns like a pot of boiling water, so they use up almost all of their fuel, sipping it slowly for trillions of years.' },
      { type: 'planet', label: 'Strange Worlds', params: { kind: 'rock', colorA: '#5a2a1a', colorB: '#a05a3a' }, camera: { dist: [34, 24], height: [6, 3], orbit: 0.08 },
        text: 'Many red dwarfs host rocky planets. But violent flares and tidal locking make their habitability one of astronomy’s great open questions.' },
      { type: 'star', label: 'The Last Stars', params: { color: '#ff7a3a', radius: 3, colorTo: '#9cc0ff' }, camera: { dist: [30, 20], height: [4, 2], orbit: 0.05 },
        text: 'The universe is too young for any red dwarf to have died. They will be the last stars still shining, long after the Sun is gone.' },
    ],
  },
  {
    id: 'milky-way-andromeda',
    title: 'When the Milky Way Collides with Andromeda',
    subtitle: 'four and a half billion years from now',
    beats: [
      { type: 'galaxy', label: 'Our Galaxy', params: { arms: 2, twist: 3.4 }, camera: { dist: [180, 130], height: [100, 55], orbit: 0.05 },
        text: 'The Milky Way is a spiral of a few hundred billion stars, about a hundred thousand light years across.' },
      { type: 'galaxy', label: 'Andromeda', params: { arms: 2, twist: 4.2, palette: ['#c8d6ff', '#ffd9a8', '#ffffff'] }, camera: { dist: [200, 140], height: [60, 30], orbit: 0.06 },
        text: 'Two and a half million light years away lies Andromeda, an even bigger spiral, and it is coming toward us at a hundred and ten kilometers per second.' },
      { type: 'galaxy', label: 'First Contact', params: { form: 1, arms: 3 }, camera: { dist: [220, 160], height: [110, 70], orbit: 0.05 },
        text: 'In about four and a half billion years, the galaxies will collide. Tidal forces will tear long streams of stars into space.' },
      { type: 'nebula', label: 'A Burst of New Stars', params: { collapse: 1, palette: ['#5ef2ff', '#8a5bff', '#ff6fd8'] }, camera: { dist: [130, 80], height: [30, 15], orbit: 0.05 },
        text: 'The stars themselves almost never touch, but the colliding gas clouds will trigger a spectacular wave of star formation.' },
      { type: 'blackhole', label: 'Milkomeda', params: { color: '#ffb36b' }, camera: { dist: [100, 60], height: [16, 7], orbit: 0.06 },
        text: 'Their central black holes will merge, and the two spirals will settle into one giant elliptical galaxy, sometimes called Milkomeda.' },
    ],
  },
  {
    id: 'end-of-universe',
    title: 'How the Universe Will End',
    subtitle: 'the long dark future',
    beats: [
      { type: 'galaxy', label: 'The Age of Stars', params: { arms: 4, twist: 3.6 }, camera: { dist: [170, 120], height: [100, 50], orbit: 0.05 },
        text: 'We live in the age of stars. But the gas that builds new stars is slowly running out, and the universe keeps expanding faster and faster.' },
      { type: 'star', label: 'The Last Sunset', params: { color: '#ff7a3a', radius: 4, colorTo: '#5a1a0a' }, camera: { dist: [35, 25], height: [4, 2], orbit: 0.05 },
        text: 'In a hundred trillion years, the last red dwarfs will burn out. Galaxies will fade to darkness.' },
      { type: 'star', label: 'Black Dwarfs', params: { color: '#dfe8ff', radius: 1.4, colorTo: '#202430', flares: false }, camera: { dist: [22, 12], height: [3, 1], orbit: 0.05 },
        text: 'White dwarfs will cool into cold black cinders. The universe will be filled with dead stars and wandering planets.' },
      { type: 'blackhole', label: 'The Black Hole Era', params: { color: '#8a5a3a' }, camera: { dist: [90, 50], height: [14, 6], orbit: 0.06 },
        text: 'For an almost unimaginable stretch of time, black holes will be the only giants left, slowly evaporating through Hawking radiation.' },
      { type: 'bigbang', label: 'Heat Death', camera: { dist: [40, 300], height: [8, 60], orbit: 0.03 },
        text: 'Finally, even they will be gone. A cold, dark, perfectly even universe, where nothing ever happens again. Unless physics has one more surprise left.' },
    ],
  },
];

export { NEBULA_PALETTES };

// Music videos of 3–4 minutes: several topics chained into one story, one soundtrack.
// Pin a track with `music`, otherwise tracks from music/ are assigned round-robin.
export const COMPILATIONS = [
  { id: 'life-of-a-star', title: 'The Life of a Star', subtitle: 'from a cold cloud to a black hole',
    topics: ['star-birth', 'massive-star-death'], music: 'music/life-of-a-star.mp3' },
  { id: 'big-bang-to-earth', title: 'From the Big Bang to Earth', subtitle: '13.8 billion years in minutes',
    topics: ['galaxy-formation', 'solar-system'], music: 'music/big-bang-to-earth.mp3' },
  { id: 'fate-of-the-sun', title: 'The Fate of Our Sun', subtitle: 'birth, life and death of our star',
    topics: ['sun-life-cycle', 'habitable-earth'], music: 'music/fate-of-the-sun.mp3' },
  { id: 'cosmic-monsters', title: 'Cosmic Monsters', subtitle: 'neutron stars and black holes',
    topics: ['neutron-star', 'inside-black-hole'], music: 'music/cosmic-monsters.mp3' },
  { id: 'worlds-are-born', title: 'How Worlds Are Born', subtitle: 'planets, moons and giants',
    topics: ['moon-formation', 'jupiter-giant'], music: 'music/worlds-are-born.mp3' },
  { id: 'cosmic-dawn', title: 'Cosmic Dawn', subtitle: 'the first stars and galaxies',
    topics: ['first-stars', 'galaxy-formation'], music: 'music/cosmic-dawn.mp3' },
  { id: 'end-of-everything', title: 'The End of Everything', subtitle: 'the last stars and the long dark',
    topics: ['red-dwarfs', 'end-of-universe'], music: 'music/end-of-everything.mp3' },
  { id: 'cosmic-alchemy', title: 'Cosmic Alchemy', subtitle: 'how dying stars forge gold',
    topics: ['massive-star-death', 'origin-of-gold'], music: 'music/cosmic-alchemy.mp3' },
  { id: 'galaxies-collide', title: 'When Galaxies Collide', subtitle: 'the Milky Way meets Andromeda',
    topics: ['milky-way-andromeda', 'inside-black-hole'], music: 'music/galaxies-collide.mp3' },
  { id: 'birth-of-the-solar-system', title: 'Birth of the Solar System', subtitle: 'from dust to planets and moons',
    topics: ['solar-system', 'moon-formation'], music: 'music/birth-of-the-solar-system.mp3' },
  { id: 'stellar-corpses', title: 'Stellar Corpses', subtitle: 'white dwarfs, neutron stars, pulsars',
    topics: ['sun-life-cycle', 'neutron-star'], music: 'music/stellar-corpses.mp3' },
  { id: 'star-nurseries', title: 'Star Nurseries', subtitle: 'where suns are born',
    topics: ['star-birth', 'red-dwarfs'], music: 'music/star-nurseries.mp3' },
  { id: 'into-the-black-hole', title: 'Into the Black Hole', subtitle: 'beyond the event horizon',
    topics: ['inside-black-hole', 'end-of-universe'], music: 'music/into-the-black-hole.mp3' },
  { id: 'living-planet', title: 'The Living Planet', subtitle: 'how Earth came alive',
    topics: ['jupiter-giant', 'habitable-earth'], music: 'music/living-planet.mp3' },
  { id: 'universe-in-3-minutes', title: 'The Universe in 3 Minutes', subtitle: '13.8 billion years, one track',
    topics: ['first-stars', 'star-birth', 'solar-system'], music: 'music/universe-in-3-minutes.mp3' },
];
